### ISSUE TITLE
Weird behaviour with negative numbers

### ISSUE THREAD

**Issue by benthillerkus** [millennIumAMbiguity/processing-formatter#5]
**Describe the bug**
For negative numbers, the extension seems to insert a space between the number and the sign (if the insert spaces option is turned on or off doesn't seem to make a difference here; though I don't think this is desirable behavior either way) and then proceeds to insert and remove a space left or the negative sign with each formatting run.

**To Reproduce**
1. Type a negative number anywhere, for example on an empty line `-15`
2. Format. The line will turn into ` - 15`
3. Format again. The line will turn into `- 15`
4. Goto 2.

**Expected behavior**
For the screenshot I've shared, the expected formatting would in my opinion be:
```Java
········triangle(-10, 10, 0, -20, 10, 10);
```

**Screenshots**
![2021-05-12_20-56-44](https://user-images.githubusercontent.com/29630575/118029820-d36a6980-b364-11eb-9505-c3ebd1b4a130.gif)

**Settings and Version information**
- Insert spaces: yes
- Formatter version: v0.4.1
- VS Code version: 1.56.1

**Additional context**
Thanks for smashing that other bug yesterday so quickly <3

**Comment by millennIumAMbiguity** [comment]
This issue has now been resolved. Thank you @benthillerkus for your continued help in finding issues/bugs on this project!
