### ISSUE TITLE
[feature-request] Add semicolon at end of statements

### ISSUE THREAD

**Issue by artze** [millennIumAMbiguity/processing-formatter#7]
I think it will be a good idea to auto-add missing semicolons at end of line during format. It's quite a common issue to miss out on semicolons...

**Is your feature request related to a problem? Please describe.**
Missing semi-colons causing processing to terminate.

**Describe the solution you'd like**
Auto-add semicolons at end of line during format.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

I will be interested to help out with this feature if you can give me some pointers on how it could be implemented on this ext!

**Comment by millennIumAMbiguity** [comment]
Interesting idea, it might appear as an option (_disabled by default_) by ~~v5~~ v0.5.0

**Comment by artze** [comment]
@millennIumAMbiguity Don't quite get what you mean there. Did you mean v5 of a dependency? If so, which one?

**Comment by millennIumAMbiguity** [comment]
My bad, meant that it might be a feature in processing formatter v0.5.0

**Comment by millennIumAMbiguity** [comment]
After further consideration, this is not something that should be part of a formatter.
